### ISSUE TITLE
broken regex post v1.6

### ISSUE THREAD

**Issue by rmwb** [hellais/TAILS-OSX#73]
the stable download folder currently contains v1.5.1 and v1.6
http://dl.amnesia.boum.org/tails/stable/
so the TAILS_VERSION variable at line 13 of create-image.sh ends up being a bit wrong

tails-i386-1.5.1
tails-i386-1.6

TAILS_VERSION=$(curl -s http://dl.amnesia.boum.org/tails/stable/ | sed -n "s/^.*\(tails-i386-[0-9.]*\).*$/\1/p")

my regex skills are low... somebody please help...

**Comment by pzp1997** [comment]
The problem is now resolved. ``tails-i386-1.5.1`` was moved to http://dl.amnesia.boum.org/tails/obsolete/ (where it should have been), leaving ``tails-i386-1.6`` as the only version in http://dl.amnesia.boum.org/tails/stable/.

**Comment by rmwb** [comment]
looks good now :)
