### ISSUE TITLE
Link redirects to malware

### ISSUE THREAD

**Issue by Calefornia** [hellais/TAILS-OSX#76]
EDIT: For some reason, it's not giving me weird sites or files anymore, but the site is dead anyway.
----------
This link listed in the Readme file redirects to a variety of spammy sites. It sometimes auto-downloads a fake flash player installer .dmg, or it'll show virus scanning nonsense.
http://fedorasolved.org/Members/jmontleon/installing-fedora-16-on-macbooks-using-grub2-efi
The domain is now for sale:
http://fedorasolved.org/

**Comment by hellais** [comment]
Hi, I fixed the link by pointing it to the archive page. However keep in mind that the information in here is now very much out of date and you should be following the official TAILS guide for macOS on their site.
I added a link to it in the Readme.
